Update security-check.yml

diff --git a/.github/workflows/security-check.yml b/.github/workflows/security-check.yml
--- a/.github/workflows/security-check.yml
+++ b/.github/workflows/security-check.yml
@@ -34,7 +34,7 @@ jobs:
       - name: Configurar entornoo
         run: |
           # Agregar la entrada al archivo known_hosts usando el fingerprint obtenido
-          echo "192.168.9.53 ssh-rsa AAAAB3N...RRGJ80jh9grh3Q6v5J8GFkA5pdrpvhDbYV5BPaMD88I" >> ~/.ssh/known_hosts || (echo "Error al agregar la entrada al archivo known_hosts" && exit 1)
+          echo "192.168.9.53 ssh-rsa RRGJ80jh9grh3Q6v5J8GFkA5pdrpvhDbYV5BPaMD88I" >> ~/.ssh/known_hosts || (echo "Error al agregar la entrada al archivo known_hosts" && exit 1)
         shell: /usr/bin/bash -e {0}
         env:
           COMPOSER_PROCESS_TIMEOUT: 0
