Update security-check.yml

diff --git a/.github/workflows/security-check.yml b/.github/workflows/security-check.yml
--- a/.github/workflows/security-check.yml
+++ b/.github/workflows/security-check.yml
@@ -31,15 +31,12 @@ jobs:
         with:
           lock: ./composer.lock
 
-      - name: Debug SSH_PRIVATE_KEY
-        run: echo "$SSH_PRIVATE_KEY"
-
       - name: Configurar entorno
         run: |
           mkdir -p ~/.ssh
-          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan 192.168.9.53 >> ~/.ssh/known_hosts
+          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa || (echo "Error al escribir la clave privada" && exit 1)
+          chmod 600 ~/.ssh/id_rsa || (echo "Error al cambiar los permisos de la clave privada" && exit 1)
+          ssh-keyscan 192.168.9.53 >> ~/.ssh/known_hosts || (echo "Error al agregar la entrada al archivo known_hosts" && exit 1)
         shell: /usr/bin/bash -e {0}
         env:
           COMPOSER_PROCESS_TIMEOUT: 0
